In [8]:
import numpy as np
A = np.array([[0,1,4,1],
              [3,4,-1,-1],
              [1,-4,1,5],
              [2,-2,1,3]],float)
v = np.array([-4,3,9,7],float)
N = len(v)

print(A, "this is A1")

for i in range(0,N-1): ## loop through columns 
    for j in range(i+1,N): ## loop through the rows 
        if A[i,i] == 0:
            print("pivoting")
            break
            
        k = A[j,i] / A[i,i]
        A[j,:] = A[j,:] - k*A[i,:]
        v[j] = v[j] - k*v[i]
    

# for k in range(N):
#     for i in range(k,N):
#          if abs(A[i][k]) > abs(A[k][k]):
#             A[k],A[i] = A[i],A[k]
#          else:
#             pass
        
print(A, "this is A2")

for m in range(N):
    div = A[m,m]
    A[m,:] /= div
    v[m] /= div
    
    for i in range(m+1,N):
        mult = A[i,m]
        A[i,:] -= mult*A[m,:]
        v[i] -= mult*v[m]
        
x = np.empty(N,float)

for m in range(N-1,-1,-1):
    x[m] = v[m]
    for i in range(m+1,N):
        x[m] -= A[m,i]*x[i]
        
print(A)
print(x)

[[ 0.  1.  4.  1.]
 [ 3.  4. -1. -1.]
 [ 1. -4.  1.  5.]
 [ 2. -2.  1.  3.]] this is A1
pivoting
pivoting
[[ 0.   1.   4.   1. ]
 [ 3.   4.  -1.  -1. ]
 [ 4.   0.   0.   4. ]
 [ 3.5  0.   0.5  2.5]] this is A2
[[nan inf inf inf]
 [nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]]
[nan nan nan nan]


<ipython-input-8-1d8c3b29b0ef>:33: RuntimeWarning: divide by zero encountered in true_divide
  A[m,:] /= div
<ipython-input-8-1d8c3b29b0ef>:33: RuntimeWarning: invalid value encountered in true_divide
  A[m,:] /= div
<ipython-input-8-1d8c3b29b0ef>:34: RuntimeWarning: divide by zero encountered in double_scalars
  v[m] /= div
<ipython-input-8-1d8c3b29b0ef>:34: RuntimeWarning: invalid value encountered in double_scalars
  v[m] /= div
